name: "build-and-check"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install
        run: yarn install --no-progress --non-interactive --skip-integrity-check
      - name: Build
        run: yarn build
      - name: Check
        run: yarn ci
    env:
      CI: true
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_COOKIE_SECRET: ${{ secrets.AUTH0_COOKIE_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
      HASURA_URL: ${{ secrets.HASURA_URL }}
